In [1]:
from glob import glob 
import pandas as pd 
import pickle as p

from util import identify_spec, identify_model_id, identify_task

In [4]:
print( "res_models/ex_BS/IMDB_distbase_N_pro/e20do5_epoch18/"[44:])

epoch18/

In [5]:
acc_df = pd.DataFrame({ "batch":[], "accuracy":[], "recall":[], "precision":[], "f1":[], "spec":[], "model_id":[], "task":[]})

for dlem in glob("res_models/ex_BS/*/*['epoch']*/"):
    print(dlem)
    spec =  identify_spec(dlem)
    model_id = identify_model_id(dlem)
    task = identify_task(dlem) 
    print(task, model_id, spec)
        
    for elem in glob(dlem+'/*'):
        
        if 'evaluation' in elem and not '.txt' in elem:
            print(elem)

            if 'original' in elem:
                df = pd.read_pickle(elem)
                df['test_data'] = 'original'
                
            else:
                df = pd.read_pickle(elem)
                df['test_data'] = 'equal'
            df['spec'] = spec
            df['model_id'] = model_id
            df['task'] = task
            
           # if acc_df==False:
            #    acc_df = df 
            #else:
            acc_df = pd.concat([acc_df, df])

res_models/ex_BS/IMDB_albertbase_mix_pro_11_24_2151_LR1/e2do5_epoch1/
IMDB albertbase mix_pro
res_models/ex_BS/IMDB_albertbase_mix_pro_11_24_2151_LR1/e2do5_epoch0/
IMDB albertbase mix_pro
res_models/ex_BS/IMDB_albertbase_mix_pro_11_24_2151_LR1/e2do5_epoch0/evaluation_mix_pro
res_models/ex_BS/IMDB_albertbase_mix_pro_11_24_2151_LR1/e2do5_epoch0/evaluation_original
res_models/ex_BS/IMDB_albertbase_original_11_24_2034_LR1/e2do5_epoch1/
IMDB albertbase original
res_models/ex_BS/IMDB_albertbase_original_11_24_2034_LR1/e2do5_epoch0/
IMDB albertbase original
res_models/ex_BS/IMDB_albertbase_original_11_24_2034_LR1/e2do5_epoch0/evaluation_original
res_models/ex_BS/IMDB_albertbase_N_weat_11_24_2113_LR1/e2do5_epoch1/
IMDB albertbase N_weat
res_models/ex_BS/IMDB_albertbase_N_weat_11_24_2113_LR1/e2do5_epoch0/
IMDB albertbase N_weat
res_models/ex_BS/IMDB_albertbase_N_weat_11_24_2113_LR1/e2do5_epoch0/evaluation_original
res_models/ex_BS/IMDB_albertbase_N_weat_11_24_2113_LR1/e2do5_epoch0/evaluation_N_weat
res_models/ex_BS/IMDB_albertbase_N_all_11_24_2132_LR1/e2do5_epoch1/
IMDB albertbase N_all
res_models/ex_BS/IMDB_albertbase_N_all_11_24_2132_LR1/e2do5_epoch0/
IMDB albertbase N_all
res_models/ex_BS/IMDB_albertbase_N_all_11_24_2132_LR1/e2do5_epoch0/evaluation_N_all
res_models/ex_BS/IMDB_albertbase_N_all_11_24_2132_LR1/e2do5_epoch0/evaluation_original
res_models/ex_BS/IMDB_albertbase_N_pro_11_24_2053_LR1/e2do5_epoch1/
IMDB albertbase N_pro
res_models/ex_BS/IMDB_albertbase_N_pro_11_24_2053_LR1/e2do5_epoch0/
IMDB albertbase N_pro
res_models/ex_BS/IMDB_albertbase_N_pro_11_24_2053_LR1/e2do5_epoch0/evaluation_N_pro
res_models/ex_BS/IMDB_albertbase_N_pro_11_24_2053_LR1/e2do5_epoch0/evaluation_original
res_models/ex_BS/writer/IMDB_albertbase_N_pro_11_24_2053_LR1_e2do5/
IMDB albertbase N_pro
res_models/ex_BS/writer/IMDB_albertbase_original_11_24_2034_LR1_e2do5/
IMDB albertbase original
res_models/ex_BS/writer/IMDB_albertbase_mix_all_11_24_2308_LR1_e2do5/
IMDB albertbase mix_all
res_models/ex_BS/writer/IMDB_albertbase_mix_weat_11_24_2230_LR1_e2do5/
IMDB albertbase mix_weat
res_models/ex_BS/writer/IMDB_albertbase_N_weat_11_24_2113_LR1_e2do5/
IMDB albertbase N_weat
res_models/ex_BS/writer/IMDB_albertbase_N_all_11_24_2132_LR1_e2do5/
IMDB albertbase N_all
res_models/ex_BS/writer/IMDB_albertbase_mix_pro_11_24_2151_LR1_e2do5/
IMDB albertbase mix_pro
res_models/ex_BS/IMDB_albertbase_mix_all_11_24_2308_LR1/e2do5_epoch1/
IMDB albertbase mix_all
res_models/ex_BS/IMDB_albertbase_mix_all_11_24_2308_LR1/e2do5_epoch0/
IMDB albertbase mix_all
res_models/ex_BS/IMDB_albertbase_mix_all_11_24_2308_LR1/e2do5_epoch0/evaluation_mix_all
res_models/ex_BS/IMDB_albertbase_mix_all_11_24_2308_LR1/e2do5_epoch0/evaluation_original
res_models/ex_BS/IMDB_albertbase_mix_weat_11_24_2230_LR1/e2do5_epoch1/
IMDB albertbase mix_weat
res_models/ex_BS/IMDB_albertbase_mix_weat_11_24_2230_LR1/e2do5_epoch0/
IMDB albertbase mix_weat
res_models/ex_BS/IMDB_albertbase_mix_weat_11_24_2230_LR1/e2do5_epoch0/evaluation_mix_weat
res_models/ex_BS/IMDB_albertbase_mix_weat_11_24_2230_LR1/e2do5_epoch0/evaluation_original

In [6]:
acc_df = pd.DataFrame({ "batch":[], "accuracy":[], "recall":[], "precision":[], "f1":[], "spec":[], "model_id":[], "task":[]})

for dlem in glob("res_models/ex_BS/*/*['epoch']*/"):
    spec =  identify_spec(elem)
    if type(spec)==list: 
        spec.remove('original')
        assert(len(spec)==1)
        spec = spec[0]
    print(model_id, spec)
    model_id = identify_model_id(elem)
    task = identify_task(elem) 
    
    for elem in glob(dlem+'/*'):
        
        if 'evaluation' in elem and not '.txt' in elem:
            print(elem)            
            if 'original' in elem:
                df = pd.read_pickle(elem)
                df['test_data'] = 'original'
                
            else:
                df = pd.read_pickle(elem)
                df['test_data'] = 'equal'
            df['spec'] = spec
            df['model_id'] = model_id
            df['task'] = task
            
           # if acc_df==False:
            #    acc_df = df 
            #else:
            acc_df = pd.concat([acc_df, df])
acc_df.loc[acc_df.spec=='original', "test_data"]='equal'

albertbase mix_weat
albertbase mix_pro
res_models/ex_BS/IMDB_albertbase_mix_pro_11_24_2151_LR1/e2do5_epoch0/evaluation_mix_pro
res_models/ex_BS/IMDB_albertbase_mix_pro_11_24_2151_LR1/e2do5_epoch0/evaluation_original
albertbase mix_pro
albertbase original
res_models/ex_BS/IMDB_albertbase_original_11_24_2034_LR1/e2do5_epoch0/evaluation_original
albertbase original
albertbase N_weat
res_models/ex_BS/IMDB_albertbase_N_weat_11_24_2113_LR1/e2do5_epoch0/evaluation_original
res_models/ex_BS/IMDB_albertbase_N_weat_11_24_2113_LR1/e2do5_epoch0/evaluation_N_weat
albertbase N_weat
albertbase N_all
res_models/ex_BS/IMDB_albertbase_N_all_11_24_2132_LR1/e2do5_epoch0/evaluation_N_all
res_models/ex_BS/IMDB_albertbase_N_all_11_24_2132_LR1/e2do5_epoch0/evaluation_original
albertbase N_all
albertbase N_pro
res_models/ex_BS/IMDB_albertbase_N_pro_11_24_2053_LR1/e2do5_epoch0/evaluation_N_pro
res_models/ex_BS/IMDB_albertbase_N_pro_11_24_2053_LR1/e2do5_epoch0/evaluation_original
albertbase N_pro
albertbase N_pro
albertbase original
albertbase mix_all
albertbase mix_weat
albertbase N_weat
albertbase N_all
albertbase mix_pro
albertbase mix_all
res_models/ex_BS/IMDB_albertbase_mix_all_11_24_2308_LR1/e2do5_epoch0/evaluation_mix_all
res_models/ex_BS/IMDB_albertbase_mix_all_11_24_2308_LR1/e2do5_epoch0/evaluation_original
albertbase mix_all
albertbase mix_weat
res_models/ex_BS/IMDB_albertbase_mix_weat_11_24_2230_LR1/e2do5_epoch0/evaluation_mix_weat
res_models/ex_BS/IMDB_albertbase_mix_weat_11_24_2230_LR1/e2do5_epoch0/evaluation_original

In [7]:
#acc_df=acc_df.sort_values(['model_id', 'spec'])
acc_df

,batch,accuracy,recall,precision,f1,spec,model_id,task,test_data
0,final,0.5,1.0,0.5,0.666667,mix_pro,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,mix_pro,albertbase,IMDB,original
0,final,0.5,1.0,0.5,0.666667,original,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,N_weat,albertbase,IMDB,original
0,final,0.5,1.0,0.5,0.666667,N_weat,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,N_all,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,N_all,albertbase,IMDB,original
0,final,0.5,1.0,0.5,0.666667,N_pro,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,N_pro,albertbase,IMDB,original
0,final,0.5,1.0,0.5,0.666667,mix_all,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,mix_all,albertbase,IMDB,original
0,final,0.5,1.0,0.5,0.666667,mix_weat,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,mix_weat,albertbase,IMDB,original

In [8]:
print(pd.get_option("display.max_columns"))
pd.set_option("display.max_rows", None)

20

In [9]:
pd.set_option("display.max_rows", None)

In [10]:
acc_df.shape

(13, 9)

In [17]:
acc_df.head()

,batch,accuracy,recall,precision,f1,spec,model_id,task,test_data
0,final,0.5,1.0,0.5,0.666667,mix_pro,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,mix_pro,albertbase,IMDB,original
0,final,0.5,1.0,0.5,0.666667,original,albertbase,IMDB,equal
0,final,0.5,1.0,0.5,0.666667,N_weat,albertbase,IMDB,original
0,final,0.5,1.0,0.5,0.666667,N_weat,albertbase,IMDB,equal

In [18]:
acc_df.to_pickle('res_results/IMDB_evaluation_df')

In [20]:
specs = ["N_pro", "N_weat", "N_all", "mix_pro", "mix_weat", "mix_all", "original" ]
    
model_ids = ["albertbase", "albertlarge", "bertbase", "bertlarge", "distbase", "robertabase", "robertalarge"]

for model in model_ids:
    for spec in specs:
        df = acc_df
        df = df.loc[(df['spec']== spec) & (df['model_id'] == model ),['accuracy','recall', 'precision', 'f1', 'test_data']]
        print('### ### ### ### ### ')
        print(model, spec)
        
        acc_l = df['accuracy'].tolist()
        rec_l = df['recall'].tolist()
        pre_l = df['precision'].tolist()
        f1_l = df['f1'].tolist()
        teda_l = df['test_data'].tolist()
        if len(teda_l) >0:
            if len(teda_l) ==1 : 
                print('only one line --- ')
            else:
                if teda_l[0] == "original":
                    print('ERROR: messed up')
                    #factor = 1
                #elif teda_l[1] == "original":
                #    factor = -1
                
                # print(factor)
                print('accuracy', acc_l[0]- acc_l[1], 'recall', rec_l[0]- rec_l[1], 'precision', pre_l[0]- pre_l[1], 'f1', f1_l[0]-f1_l[1])
                #print('test_data', teda_l[0]-teda_l[1])

### ### ### ### ###
albertbase N_pro
accuracy 0.0 recall 0.0 precision 0.0 f1 0.0
### ### ### ### ###
albertbase N_weat
ERROR: messed up
accuracy 0.0 recall 0.0 precision 0.0 f1 0.0
### ### ### ### ###
albertbase N_all
accuracy 0.0 recall 0.0 precision 0.0 f1 0.0
### ### ### ### ###
albertbase mix_pro
accuracy 0.0 recall 0.0 precision 0.0 f1 0.0
### ### ### ### ###
albertbase mix_weat
accuracy 0.0 recall 0.0 precision 0.0 f1 0.0
### ### ### ### ###
albertbase mix_all
accuracy 0.0 recall 0.0 precision 0.0 f1 0.0
### ### ### ### ###
albertbase original
only one line ---
### ### ### ### ###
albertlarge N_pro
### ### ### ### ###
albertlarge N_weat
### ### ### ### ###
albertlarge N_all
### ### ### ### ###
albertlarge mix_pro
### ### ### ### ###
albertlarge mix_weat
### ### ### ### ###
albertlarge mix_all
### ### ### ### ###
albertlarge original
### ### ### ### ###
bertbase N_pro
### ### ### ### ###
bertbase N_weat
### ### ### ### ###
bertbase N_all
### ### ### ### ###
bertbase mix_pro
### ### ### ### ###
bertbase mix_weat
### ### ### ### ###
bertbase mix_all
### ### ### ### ###
bertbase original
### ### ### ### ###
bertlarge N_pro
### ### ### ### ###
bertlarge N_weat
### ### ### ### ###
bertlarge N_all
### ### ### ### ###
bertlarge mix_pro
### ### ### ### ###
bertlarge mix_weat
### ### ### ### ###
bertlarge mix_all
### ### ### ### ###
bertlarge original
### ### ### ### ###
distbase N_pro
### ### ### ### ###
distbase N_weat
### ### ### ### ###
distbase N_all
### ### ### ### ###
distbase mix_pro
### ### ### ### ###
distbase mix_weat
### ### ### ### ###
distbase mix_all
### ### ### ### ###
distbase original
### ### ### ### ###
robertabase N_pro
### ### ### ### ###
robertabase N_weat
### ### ### ### ###
robertabase N_all
### ### ### ### ###
robertabase mix_pro
### ### ### ### ###
robertabase mix_weat
### ### ### ### ###
robertabase mix_all
### ### ### ### ###
robertabase original
### ### ### ### ###
robertalarge N_pro
### ### ### ### ###
robertalarge N_weat
### ### ### ### ###
robertalarge N_all
### ### ### ### ###
robertalarge mix_pro
### ### ### ### ###
robertalarge mix_weat
### ### ### ### ###
robertalarge mix_all
### ### ### ### ###
robertalarge original

In [21]:
print(acc_df.columns)

Index(['batch', 'accuracy', 'recall', 'precision', 'f1', 'spec', 'model_id',
       'task', 'test_data'],
      dtype='object')

In [22]:
acc_df.loc[acc_df.spec=='original', "test_data"]='equal'

In [23]:
acc_df_short = acc_df.loc[acc_df.test_data=='equal', ['model_id', 'spec', 'accuracy', 'recall', 'precision', 'f1' ]]
acc_df_short= acc_df_short.sort_values(by=["model_id", "spec"])
acc_df_short

     model_id      spec  accuracy  recall  precision        f1
0  albertbase     N_all       0.5     1.0        0.5  0.666667
0  albertbase     N_pro       0.5     1.0        0.5  0.666667
0  albertbase    N_weat       0.5     1.0        0.5  0.666667
0  albertbase   mix_all       0.5     1.0        0.5  0.666667
0  albertbase   mix_pro       0.5     1.0        0.5  0.666667
0  albertbase  mix_weat       0.5     1.0        0.5  0.666667
0  albertbase  original       0.5     1.0        0.5  0.666667

In [24]:
print(acc_df_short.to_latex())

\begin{tabular}{lllrrrr}
\toprule
{} &    model\_id &      spec &  accuracy &  recall &  precision &        f1 \\
\midrule
0 &  albertbase &     N\_all &       0.5 &     1.0 &        0.5 &  0.666667 \\
0 &  albertbase &     N\_pro &       0.5 &     1.0 &        0.5 &  0.666667 \\
0 &  albertbase &    N\_weat &       0.5 &     1.0 &        0.5 &  0.666667 \\
0 &  albertbase &   mix\_all &       0.5 &     1.0 &        0.5 &  0.666667 \\
0 &  albertbase &   mix\_pro &       0.5 &     1.0 &        0.5 &  0.666667 \\
0 &  albertbase &  mix\_weat &       0.5 &     1.0 &        0.5 &  0.666667 \\
0 &  albertbase &  original &       0.5 &     1.0 &        0.5 &  0.666667 \\
\bottomrule
\end{tabular}

/var/folders/md/bfz8h2w96gz5p8cm9hf777vm0000gn/T/ipykernel_30125/3276347738.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(acc_df_short.to_latex())

In [25]:
acc_df_short

     model_id      spec  accuracy  recall  precision        f1
0  albertbase     N_all       0.5     1.0        0.5  0.666667
0  albertbase     N_pro       0.5     1.0        0.5  0.666667
0  albertbase    N_weat       0.5     1.0        0.5  0.666667
0  albertbase   mix_all       0.5     1.0        0.5  0.666667
0  albertbase   mix_pro       0.5     1.0        0.5  0.666667
0  albertbase  mix_weat       0.5     1.0        0.5  0.666667
0  albertbase  original       0.5     1.0        0.5  0.666667